USE Sucos;


/*CREATING TABLES*/
CREATE TABLE tbCliente(
	CPF VARCHAR(11),
    NOME VARCHAR(100),
    ENDERECO1 VARCHAR(150),
    ENDERECO2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(8),
    IDADE SMALLINT,
    SEXO VARCHAR(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA BIT(1)
);

CREATE TABLE TABELA_DE_VENDEDORES(
	MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    PERCENTUAL_COMISSAO FLOAT,
    DATA_ADMISSAO DATE,
    DE_FERIAS BIT(1)
);


/*ALTERING A TABLE*/
ALTER TABLE tbproduto ADD PRIMARY KEY (PRODUTO);

ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);
ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);


/*DELETING A TABLE*/
DROP TABLE tabela_de_vendedores;

