USE sucos_vendas;

SELECT VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO, CLIENTE.BAIRRO AS CLIENTE_BAIRRO FROM tabela_de_vendedores VENDEDOR
FULL JOIN tabela_de_clientes CLIENTE ON VENDEDOR.BAIRRO = CLIENTE.BAIRRO GROUP BY CLIENTE.CPF;

SELECT VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO, CLIENTE.BAIRRO AS CLIENTE_BAIRRO FROM tabela_de_vendedores VENDEDOR, 
tabela_de_clientes CLIENTE; /*CROSS JOIN RETORNA O PRODUTO CARTESIANO DAS DUAS TABELAS*/
