USE sucos_vendas;

SELECT VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO, CLIENTE.BAIRRO AS CLIENTE_BAIRRO FROM tabela_de_vendedores VENDEDOR,
FULL JOIN tabela_de_clientes CLIENTE ON VENDEDOR.BAIRRO = CLIENTE.BAIRRO GROUP BY CLIENTE.CPF;

SELECT VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO, CLIENTE.BAIRRO AS CLIENTE_BAIRRO FROM tabela_de_vendedores VENDEDOR, 
tabela_de_clientes CLIENTE; /*CROSS JOIN RETORNA O PRODUTO CARTESIANO DAS DUAS TABELAS*/

SELECT 	VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO,
		VENDEDOR.NOME AS VENDEDOR_NOME,
        VENDEDOR.DE_FERIAS,
		CLIENTE.BAIRRO AS CLIENTE_BAIRRO,
        CLIENTE.NOME AS CLIENTE_NOME
FROM tabela_de_vendedores VENDEDOR INNER JOIN tabela_de_clientes CLIENTE
ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO;

SELECT 	VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO,
		VENDEDOR.NOME AS VENDEDOR_NOME,
        VENDEDOR.DE_FERIAS,
		CLIENTE.BAIRRO AS CLIENTE_BAIRRO,
        CLIENTE.NOME AS CLIENTE_NOME
FROM tabela_de_vendedores VENDEDOR LEFT JOIN tabela_de_clientes CLIENTE
ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO;


SELECT 	VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO,
		VENDEDOR.NOME AS VENDEDOR_NOME,
        VENDEDOR.DE_FERIAS,
		CLIENTE.BAIRRO AS CLIENTE_BAIRRO,
        CLIENTE.NOME AS CLIENTE_NOME
FROM tabela_de_vendedores VENDEDOR RIGHT JOIN tabela_de_clientes CLIENTE
ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO;

/*It doesn't work on MySql, because MySql doesn't support the command FULL*/
SELECT tabela_de_vendedores.BAIRRO,
	tabela_de_vendedores.NOME, DE_FERIAS,
    tabela_de_clientes.BAIRRO,
    tabela_de_clientes.NOME from tabela_de_vendedores FULL JOIN tabela_de_clientes
ON tabela_de_vendedores.BAIRRO = tabela_de_clientes.BAIRRO;

/*An workaround to achieve FULL JOIN in MySql: */
SELECT 	VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO,
		VENDEDOR.NOME AS VENDEDOR_NOME,
        VENDEDOR.DE_FERIAS,
		CLIENTE.BAIRRO AS CLIENTE_BAIRRO,
        CLIENTE.NOME AS CLIENTE_NOME
FROM tabela_de_vendedores VENDEDOR LEFT JOIN tabela_de_clientes CLIENTE
ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO
UNION
SELECT 	VENDEDOR.BAIRRO AS VENDEDOR_BAIRRO,
		VENDEDOR.NOME AS VENDEDOR_NOME,
        VENDEDOR.DE_FERIAS,
		CLIENTE.BAIRRO AS CLIENTE_BAIRRO,
        CLIENTE.NOME AS CLIENTE_NOME
FROM tabela_de_vendedores VENDEDOR RIGHT JOIN tabela_de_clientes CLIENTE
ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO;
