USE sucos_vendas;

SELECT embalagem, MAX(preco_de_lista) AS  maior_preco FROM tabela_de_produtos GROUP BY embalagem;

CREATE OR REPLACE VIEW `VW_EMBALAGENS_MAIS_CARAS` AS
SELECT embalagem, MAX(preco_de_lista) AS  maior_preco FROM tabela_de_produtos GROUP BY embalagem;

/*AS DUAS CONSULTAS ABAIXO RETORNARÃO O MESMO RESULTADO*/
SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM VW_EMBALAGENS_MAIS_CARAS X
WHERE X.MAIOR_PRECO > 10;

SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM
(SELECT embalagem, MAX(preco_de_lista) AS  maior_preco FROM tabela_de_produtos GROUP BY embalagem) X
WHERE X.MAIOR_PRECO > 10;

/*==== || ====*/

SELECT produto.NOME_DO_PRODUTO, produto.EMBALAGEM, produto.PRECO_DE_LISTA, X.MAIOR_PRECO
FROM TABELA_DE_PRODUTOS produto INNER JOIN VW_EMBALAGENS_MAIS_CARAS X
ON produto.EMBALAGEM = x.EMBALAGEM;

SELECT produto.NOME_DO_PRODUTO, produto.EMBALAGEM, produto.PRECO_DE_LISTA, X.MAIOR_PRECO,
FORMAT((produto.PRECO_DE_LISTA / X.MAIOR_PRECO) * 100, 2) AS PERCENTUAL
FROM TABELA_DE_PRODUTOS produto INNER JOIN VW_EMBALAGENS_MAIS_CARAS X
ON produto.EMBALAGEM = x.EMBALAGEM;


